language: ruby
rvm:
  - 2.6.0

services:
  - docker
  - postgresql


before_install:
  - docker pull ruby
  - docker pull postgres
  - docker run ruby
  - docker run postgres --name testingCrap -e POSTGRES_PASSWORD=password -d postgres

script:
  - sudo docker-compose exec guard rspec
  - rubocop
  - bundle-audit


deploy:
  provider: heroku
  api_key:
    secure: "ENCRYPTED_API_KEY"