language: ruby
rvm:
  - 2.6.0

before_script:
  - bin/setup

script:
  - sudo docker-compose exec guard rspec
  - rubocop
  - bundle-audit


deploy:
  provider: heroku
  api_key:
    secure: "ENCRYPTED_API_KEY"