language: ruby
rvm:
  - 2.6.0

services:
  - docker
  - postgresql


before_install:
  - docker pull ruby
  - docker run ruby
  - docker build -t carlad/sinatra .
  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start";
  - docker ps -a


before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - sudo docker-compose exec guard rspec
  - rubocop
  - bundle-audit


deploy:
  provider: heroku
  api_key:
    secure: "ENCRYPTED_API_KEY"